### PR TITLE
upgrade openresty to 1.19.3.1

### PR DESCRIPTION
**Pull request by dberg1**
This is a pre-requisite for ppc64le support (not included in this PR, see https://github.com/open-cluster-management/backlog/issues/10366 for details).
Also removes Makefile.openssl1.1.1j.patch as I do not see any need for it with OpenResty 1.19.3.1 (tested on x86).

### CODE REVIEW

**Comment by haoqing0110** [comment]
@dberg1 thanks for submitting this PR. 
/cc @clyang82 are we going to support 1.19.3.1 in 2.3 release?

**Comment by haoqing0110** [comment]
@dberg1 Considering there's potential FIPS requirement refer to https://github.com/open-cluster-management/backlog/issues/10366#issuecomment-804993858, would like to hold on this PR.

**Comment by haoqing0110** [comment]
@dberg1 FIPS is not planned for current release, could you help remove fips related code in PR?

**Comment by dberg1** [comment]
@haoqing0110 I have just removed the FIPS related code in PR.

**Pull request merged**
